In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE  # For handling class imbalance
#warnings
import warnings
warnings.filterwarnings('ignore')

#load dataset

In [135]:
# Load the data
train_data = pd.read_csv('/content/train_loan_data (1).csv')
test_data = pd.read_csv('/content/test_loan_data (1).csv')

In [136]:
train_data.head()

,addr_state,annual_inc,earliest_cr_line,emp_length,emp_title,fico_range_high,fico_range_low,grade,home_ownership,application_type,...,pub_rec_bankruptcies,purpose,revol_bal,revol_util,sub_grade,term,title,total_acc,verification_status,loan_status
0,CO,85000.0,Jul-97,10+ years,Deputy,744,740,E,MORTGAGE,Individual,...,0.0,debt_consolidation,5338,93.6,E1,60 months,Debt consolidation,8,Source Verified,Defaulted
1,CA,40000.0,Apr-87,10+ years,Department of Veterans Affairs,724,720,B,RENT,Individual,...,0.0,debt_consolidation,19944,60.3,B1,36 months,Credit Loan,12,Verified,Paid
2,FL,60000.0,Aug-07,10+ years,Marble polishing,679,675,B,MORTGAGE,Individual,...,0.0,debt_consolidation,23199,88.5,B5,36 months,Debt consolidation,16,Source Verified,Paid
3,IL,100742.0,Sep-80,10+ years,printer,664,660,B,MORTGAGE,Individual,...,0.0,debt_consolidation,18425,69.0,B2,36 months,Debt consolidation,19,Source Verified,Paid
4,MD,80000.0,Jul-99,10+ years,Southern Mgmt,669,665,F,RENT,Individual,...,0.0,debt_consolidation,34370,90.0,F5,60 months,Debt Connsolidation,59,Verified,Paid

In [137]:
test_data.head()

,addr_state,annual_inc,earliest_cr_line,emp_length,emp_title,fico_range_high,fico_range_low,grade,home_ownership,application_type,...,pub_rec,pub_rec_bankruptcies,purpose,revol_bal,revol_util,sub_grade,term,title,total_acc,verification_status
0,MO,50000.0,May-2012,1 year,Tower technician,719.0,715.0,C,OWN,Individual,...,0.0,0.0,debt_consolidation,2568.0,9.8,C4,36 months,Debt consolidation,11.0,Source Verified
1,HI,92000.0,Dec-2001,10+ years,Supervisor,684.0,680.0,B,RENT,Individual,...,0.0,0.0,debt_consolidation,30394.0,75.4,B2,36 months,Debt consolidation,35.0,Source Verified
2,TX,89000.0,Mar-1989,10+ years,APPLICATIONS PROGRAMMER,679.0,675.0,B,MORTGAGE,Individual,...,0.0,0.0,credit_card,38400.0,75.3,B2,60 months,Credit card refinancing,41.0,Not Verified
3,CA,33000.0,Nov-2004,9 years,San Diego Unified School District,674.0,670.0,C,RENT,Individual,...,1.0,1.0,debt_consolidation,21224.0,69.4,C1,36 months,Breathing Room,16.0,Not Verified
4,MI,35580.0,Feb-1997,NaN,NaN,704.0,700.0,B,MORTGAGE,Individual,...,0.0,0.0,debt_consolidation,3471.0,39.4,B5,36 months,debitconsolidation,19.0,Verified

#EDA(Eemp_lengthplotary Data Analysis):-

In [138]:
# Basic info
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   addr_state            80000 non-null  object
 1   annual_inc            80000 non-null  float64
 2   earliest_cr_line      80000 non-null  object
 3   emp_length            75412 non-null  object
 4   emp_title             74982 non-null  object
 5   fico_range_high       80000 non-null  int64
 6   fico_range_low        80000 non-null  int64
 7   grade                 80000 non-null  object
 8   home_ownership        80000 non-null  object
 9   application_type      80000 non-null  object
 10  initial_list_status   80000 non-null  object
 11  int_rate              80000 non-null  float64
 12  loan_amnt             80000 non-null  int64
 13  num_actv_bc_tl        76052 non-null  float64
 14  mort_acc              77229 non-null  float64
 15  tot_cur_bal           76052 non-null  float64
 16  open_acc              80000 non-null  int64
 17  pub_rec               80000 non-null  int64
 18  pub_rec_bankruptcies  79969 non-null  float64
 19  purpose               80000 non-null  object
 20  revol_bal             80000 non-null  int64
 21  revol_util            79947 non-null  float64
 22  sub_grade             80000 non-null  object
 23  term                  80000 non-null  object
 24  title                 79030 non-null  object
 25  total_acc             80000 non-null  int64
 26  verification_status   80000 non-null  object
 27  loan_status           80000 non-null  object
dtypes: float64(7), int64(7), object(14)
memory usage: 17.1+ MB
None

In [139]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   addr_state            20000 non-null  object
 1   annual_inc            20000 non-null  float64
 2   earliest_cr_line      20000 non-null  object
 3   emp_length            18742 non-null  object
 4   emp_title             18622 non-null  object
 5   fico_range_high       20000 non-null  float64
 6   fico_range_low        20000 non-null  float64
 7   grade                 20000 non-null  object
 8   home_ownership        20000 non-null  object
 9   application_type      20000 non-null  object
 10  initial_list_status   20000 non-null  object
 11  int_rate              20000 non-null  float64
 12  loan_amnt             20000 non-null  float64
 13  num_actv_bc_tl        18989 non-null  float64
 14  mort_acc              19296 non-null  float64
 15  tot_cur_bal           18989 non-null  float64
 16  open_acc              20000 non-null  float64
 17  pub_rec               20000 non-null  float64
 18  pub_rec_bankruptcies  19989 non-null  float64
 19  purpose               20000 non-null  object
 20  revol_bal             20000 non-null  float64
 21  revol_util            19987 non-null  float64
 22  sub_grade             20000 non-null  object
 23  term                  20000 non-null  object
 24  title                 19753 non-null  object
 25  total_acc             20000 non-null  float64
 26  verification_status   20000 non-null  object
dtypes: float64(14), object(13)
memory usage: 4.1+ MB

In [140]:
#check the shape of dataset train_data
print("train dataset shape:-",train_data.shape)
print("test dataset shape:-",test_data.shape)

train dataset shape:- (80000, 28)
test dataset shape:- (20000, 27)

In [141]:
#check ythe nul values
train_data.isnull().sum()

addr_state                 0
annual_inc                 0
earliest_cr_line           0
emp_length              4588
emp_title               5018
fico_range_high            0
fico_range_low             0
grade                      0
home_ownership             0
application_type           0
initial_list_status        0
int_rate                   0
loan_amnt                  0
num_actv_bc_tl          3948
mort_acc                2771
tot_cur_bal             3948
open_acc                   0
pub_rec                    0
pub_rec_bankruptcies      31
purpose                    0
revol_bal                  0
revol_util                53
sub_grade                  0
term                       0
title                    970
total_acc                  0
verification_status        0
loan_status                0
dtype: int64

In [142]:
test_data.isnull().sum()

addr_state                 0
annual_inc                 0
earliest_cr_line           0
emp_length              1258
emp_title               1378
fico_range_high            0
fico_range_low             0
grade                      0
home_ownership             0
application_type           0
initial_list_status        0
int_rate                   0
loan_amnt                  0
num_actv_bc_tl          1011
mort_acc                 704
tot_cur_bal             1011
open_acc                   0
pub_rec                    0
pub_rec_bankruptcies      11
purpose                    0
revol_bal                  0
revol_util                13
sub_grade                  0
term                       0
title                    247
total_acc                  0
verification_status        0
dtype: int64

In [143]:
#emp_length
train_data['emp_length'].unique()

array(['10+ years', nan, '3 years', '< 1 year', '1 year', '8 years',
       '7 years', '4 years', '2 years', '5 years', '6 years', '9 years'],
      dtype=object)

In [144]:
# Mapping function for 'emp_length' column to convert to float
def convert_emp_length(emp_length):
    if emp_length == '10+ years':
        return 10.0
    elif emp_length == '< 1 year':
        return 0.0
    elif isinstance(emp_length, str):  # Handles cases like '3 years', '1 year', etc.
        return float(emp_length.split()[0])
    else:
        return np.nan  # Use np.nan for missing values

# Apply the function to both train and test datasets
train_data['emp_length'] = train_data['emp_length'].apply(convert_emp_length)
test_data['emp_length'] = test_data['emp_length'].apply(convert_emp_length)

In [145]:
# Fill missing values with median for numerical columns
numerical_columns = ['emp_length', 'num_actv_bc_tl', 'mort_acc', 'tot_cur_bal', 'pub_rec_bankruptcies', 'revol_util']
for col in numerical_columns:
    train_data[col].fillna(train_data[col].median(), inplace=True)
    test_data[col].fillna(test_data[col].median(), inplace=True)

In [146]:
# Fill missing values with mode for categorical columns
categorical_columns = ['emp_title', 'title']
for col in categorical_columns:
    train_data[col].fillna(train_data[col].mode()[0], inplace=True)
    test_data[col].fillna(test_data[col].mode()[0], inplace=True)

In [147]:
#check the null values
print("check train dataset null values:-",train_data.isnull().sum().any())
print("check null values in test data:-",test_data.isnull().sum().any())

check train dataset null values:- False
check null values in test data:- False

In [148]:
#check the numerical column list
numerical_columns = train_data.select_dtypes(include=['number']).columns
print(numerical_columns)

Index(['annual_inc', 'emp_length', 'fico_range_high', 'fico_range_low',
       'int_rate', 'loan_amnt', 'num_actv_bc_tl', 'mort_acc', 'tot_cur_bal',
       'open_acc', 'pub_rec', 'pub_rec_bankruptcies', 'revol_bal',
       'revol_util', 'total_acc'],
      dtype='object')

In [149]:
# Convert the specified numerical columns to float64
train_data[numerical_columns] = train_data[numerical_columns].astype('float64')
test_data[numerical_columns] = test_data[numerical_columns].astype('float64')

In [150]:
#drop date column
train_data.drop('earliest_cr_line', axis=1, inplace=True)
test_data.drop('earliest_cr_line', axis=1, inplace=True)

In [151]:
# Apply the mapping to the loan_status column
train_data['loan_status'] = train_data['loan_status'].map({'Paid': 1,'Defaulted': 0})

#Convert categorical column in to Numerical column

In [152]:
#categorical column list
categorical_columns = train_data.select_dtypes(include=['object']).columns
print(categorical_columns)

Index(['addr_state', 'emp_title', 'grade', 'home_ownership',
       'application_type', 'initial_list_status', 'purpose', 'sub_grade',
       'term', 'title', 'verification_status'],
      dtype='object')

In [153]:
for col in categorical_columns:
    print(f"Unique values in column '{col}':")
    print(train_data[col].unique())
    print()

Unique values in column 'addr_state':
['CO' 'CA' 'FL' 'IL' 'MD' 'NY' 'PA' 'WI' 'UT' 'TX' 'AL' 'KS' 'AR' 'AZ'
 'MI' 'MN' 'LA' 'HI' 'NC' 'VT' 'OK' 'KY' 'ME' 'CT' 'AK' 'NJ' 'IN' 'GA'
 'MA' 'OR' 'NM' 'VA' 'TN' 'SC' 'NV' 'WY' 'WA' 'WV' 'MO' 'OH' 'MS' 'DC'
 'NE' 'ID' 'NH' 'RI' 'SD' 'MT' 'DE' 'ND' 'IA']

Unique values in column 'emp_title':
['Deputy' 'Department of Veterans Affairs' 'Marble polishing' ...
 'COAL MINER' 'repair tec' 'Sports Group Manager']

Unique values in column 'grade':
['E' 'B' 'F' 'D' 'C' 'A' 'G']

Unique values in column 'home_ownership':
['MORTGAGE' 'RENT' 'OWN' 'ANY' 'NONE' 'OTHER']

Unique values in column 'application_type':
['Individual' 'Joint App']

Unique values in column 'initial_list_status':
['w' 'f']

Unique values in column 'purpose':
['debt_consolidation' 'home_improvement' 'credit_card' 'other'
 'small_business' 'medical' 'major_purchase' 'car' 'vacation' 'house'
 'moving' 'wedding' 'renewable_energy' 'educational']

Unique values in column 'sub_grade':
['E1' 'B1' 'B5' 'B2' 'F5' 'D3' 'C1' 'C4' 'B4' 'D4' 'A5' 'C3' 'C2' 'E4'
 'F3' 'E2' 'A1' 'C5' 'B3' 'E5' 'A4' 'D2' 'F2' 'A2' 'A3' 'F1' 'D5' 'D1'
 'E3' 'G2' 'F4' 'G1' 'G3' 'G4' 'G5']

Unique values in column 'term':
[' 60 months' ' 36 months']

Unique values in column 'title':
['Debt consolidation' 'Credit Loan' 'Debt Connsolidation' ...
 'cr card payoff' 'Debt in one place' 'Consolidate 2012']

Unique values in column 'verification_status':
['Source Verified' 'Verified' 'Not Verified']

In [154]:
for col in categorical_columns:
    print(f"Unique values in column '{col}':")
    print(test_data[col].unique())
    print()

Unique values in column 'addr_state':
['MO' 'HI' 'TX' 'CA' 'MI' 'NJ' 'FL' 'GA' 'MD' 'AL' 'NC' 'KS' 'NY' 'OH'
 'NV' 'MA' 'CO' 'IL' 'AZ' 'WI' 'VA' 'MT' 'UT' 'PA' 'NH' 'SC' 'SD' 'CT'
 'OR' 'IN' 'OK' 'AR' 'MN' 'RI' 'AK' 'NM' 'WA' 'KY' 'TN' 'ME' 'MS' 'WV'
 'NE' 'ID' 'DE' 'LA' 'WY' 'DC' 'ND' 'VT']

Unique values in column 'emp_title':
['Tower technician' 'Supervisor' 'APPLICATIONS PROGRAMMER' ...
 'Contract & Compliance Manager' 'Manager In Training' 'rv technician']

Unique values in column 'grade':
['C' 'B' 'A' 'D' 'E' 'F' 'G']

Unique values in column 'home_ownership':
['OWN' 'RENT' 'MORTGAGE' 'ANY']

Unique values in column 'application_type':
['Individual' 'Joint App']

Unique values in column 'initial_list_status':
['f' 'w']

Unique values in column 'purpose':
['debt_consolidation' 'credit_card' 'home_improvement' 'other'
 'major_purchase' 'car' 'small_business' 'medical' 'vacation' 'wedding'
 'moving' 'renewable_energy' 'house' 'educational']

Unique values in column 'sub_grade':
['C4' 'B2' 'C1' 'B5' 'A3' 'D3' 'B3' 'B1' 'E5' 'B4' 'A4' 'F1' 'C5' 'C2'
 'F3' 'D1' 'A5' 'D5' 'E1' 'C3' 'F2' 'E4' 'A1' 'A2' 'E3' 'D2' 'E2' 'D4'
 'F4' 'G1' 'F5' 'G4' 'G5' 'G3' 'G2']

Unique values in column 'term':
[' 36 months' ' 60 months']

Unique values in column 'title':
['Debt consolidation' 'Credit card refinancing' 'Breathing Room' ...
 'Consolidation Home Improvement' 'Repurpose' 'credit card refinance loan']

Unique values in column 'verification_status':
['Source Verified' 'Not Verified' 'Verified']

In [155]:
#title and porpose of loan are same so we drop title column to reduce dimensonality
train_data.drop('title', axis=1, inplace=True)
test_data.drop('title', axis=1, inplace=True)

In [156]:
# Drop `emp_title` if it's not necessary
train_data = train_data.drop('emp_title', axis=1)
test_data = test_data.drop('emp_title', axis=1)

In [157]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Define columns to encode
cols_to_encode = ['grade', 'initial_list_status', 'application_type', 'addr_state', 'sub_grade','home_ownership', 'purpose', 'term', 'verification_status']
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Encode train and test data separately
encoded_train = encoder.fit_transform(train_data[cols_to_encode])
encoded_test = encoder.transform(test_data[cols_to_encode])

# Convert to DataFrames with feature names
encoded_train_df = pd.DataFrame(encoded_train, columns=encoder.get_feature_names_out(cols_to_encode), index=train_data.index)
encoded_test_df = pd.DataFrame(encoded_test, columns=encoder.get_feature_names_out(cols_to_encode), index=test_data.index)

# Drop original columns and add encoded columns
train_data = train_data.drop(cols_to_encode, axis=1).join(encoded_train_df)
test_data = test_data.drop(cols_to_encode, axis=1).join(encoded_test_df)

# Align columns to ensure consistency
train_data, test_data = train_data.align(test_data, fill_value=0, axis=1)

In [158]:
#shape dataset
print("train dataset shape:-",train_data.shape)
print("test dataset shape:-",test_data.shape)

train dataset shape:- (80000, 138)
test dataset shape:- (20000, 138)

In [159]:
train_data.head()

,addr_state_AK,addr_state_AL,addr_state_AR,addr_state_AZ,addr_state_CA,addr_state_CO,addr_state_CT,addr_state_DC,addr_state_DE,addr_state_FL,...,sub_grade_G3,sub_grade_G4,sub_grade_G5,term_ 36 months,term_ 60 months,tot_cur_bal,total_acc,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,319479.0,8.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,19944.0,12.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,23199.0,16.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,72651.0,19.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,64631.0,59.0,0.0,0.0,1.0

In [161]:
train_data['loan_status'].value_counts()

loan_status
1    64030
0    15970
Name: count, dtype: int64

In [162]:
test_data['loan_status'].value_counts()

loan_status
0    20000
Name: count, dtype: int64

In [165]:
#drop the loan_staus column in test dataset
test_data = test_data.drop('loan_status', axis=1)

In [163]:
# Step 1: Separate features and target in training data
X_train = train_data.drop(columns=['loan_status'])
y_train = train_data['loan_status']

In [164]:
# Step 2: Train a classifier (Random Forest in this example)
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [166]:
# Predict loan_status for the test data
test_predictions = model.predict(test_data)

***check accuracy there are no validaation dataset so we split train data to validation dataset ***

In [168]:
# Check accuracy on a validation set (split from train_data)
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
model.fit(X_train_split, y_train_split)
val_predictions = model.predict(X_val_split)
print("Validation Accuracy:", accuracy_score(y_val_split, val_predictions))
print(classification_report(y_val_split, val_predictions))

Validation Accuracy: 0.80625
              precision    recall  f1-score   support

           0       0.52      0.06      0.11      3114
           1       0.81      0.99      0.89     12886

    accuracy                           0.81     16000
   macro avg       0.67      0.52      0.50     16000
weighted avg       0.76      0.81      0.74     16000

#now predict the test dataset loan_status column using model
where  ***'Paid': 1,   'Defaulted': 0***

In [169]:
# Add predictions to test_data
test_data['predicted_loan_status'] = test_predictions
print(test_data[['predicted_loan_status']].head())

   predicted_loan_status
0                      1
1                      1
2                      1
3                      1
4                      1

In [171]:
test_data['predicted_loan_status'].value_counts()

predicted_loan_status
1    19495
0      505
Name: count, dtype: int64

In [170]:
test_data

,addr_state_AK,addr_state_AL,addr_state_AR,addr_state_AZ,addr_state_CA,addr_state_CO,addr_state_CT,addr_state_DC,addr_state_DE,addr_state_FL,...,sub_grade_G4,sub_grade_G5,term_ 36 months,term_ 60 months,tot_cur_bal,total_acc,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,predicted_loan_status
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,33395.0,11.0,0.0,1.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,229832.0,35.0,0.0,1.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,181616.0,41.0,1.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,30603.0,16.0,1.0,0.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,124597.0,19.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,30397.0,10.0,1.0,0.0,0.0,1
19996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,494439.0,30.0,0.0,1.0,0.0,1
19997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,284915.0,29.0,0.0,1.0,0.0,1
19998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,8205.0,19.0,1.0,0.0,0.0,1
19999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,48212.0,19.0,0.0,0.0,1.0,0

#save the model

In [174]:
import joblib
# Save the model to a file
joblib.dump(model, 'loan_status_model.pkl')

['loan_status_model.pkl']